### PR TITLE
delegatee -> delegate

### PR DESCRIPTION
**Pull request by Tbaut**
As discussed

### CODE REVIEW

**Review by wirednkod — APPROVED** [review]

**Comment by wirednkod** [comment]
@Tbaut Build in cloudflare is failing - and I have no access to these logs

**Comment by Tbaut** [comment]
I'll check

**Comment by Tbaut** [comment]
It was just a glitch it seems, the build was fine, the deployment wasn't. But that was just for the preview anyway. I relaunched and it worked, so merging.

**Comment by wirednkod** [comment]
Thank you!

**Pull request merged**
