### PR TITLE
UI appearance nits

### LINKED ISSUE #99: Make delegate page more appealing
If we want users to link to the delegate page directly, we need to make it nicers:
- show the name of the delegate with picture
- show the description, maybe just the short one, with a `ContentReveal` again?

otherwise landing on this isn't really appealing
image

### PR DESCRIPTION
**Pull request by goldsteinsveta**
- Closes #99 
- More compact layout. It is easier to scan for humans

Before and after:

Screenshot 2024-09-15 at 15 10 17
Screenshot 2024-09-15 at 15 10 33

---

Submission checklist:

#### Layout

- [x] Change inspected in the mobile web ui
- [x] Change inspected in dark mode

### CODE REVIEW

**Review by Tbaut — COMMENTED** [review]
Thank you so much, very much better in terms of how things feel. I left some impressions and thoughts for the "share" buttons. I think we need to think it through more.

**Comment by Tbaut** [comment]
ok some weirdness happened, and a long comment about the share button didn't make it in the review, here it is again:

I tested the UI first without looking at the code, and when I saw this big "share" button, I thought: "oh this is going to share this delegate on social media or something". 

I think alerts are a big no-no for UI, it's surprising, looks like an error, and requires an additional click. 
This button would not be useful to 99% of our users, it's only for delegates, so we should make it a lot less prominent, and place it somewhere else, not under the main CTA of the page. Maybe as a small link icon next to the title (before the title even, a little like Github links to titles?
image

In any case it needs to be thought through, and communication to delegates should be the priority to let them know that they can link directly, they are not the ones delegating, and won't discover this link themselves if we don't tell them.

**Comment by goldsteinsveta** [comment]
I've updated the share button to this:

Screenshot 2024-09-16 at 16 47 00

I wouldn't hide it completely [yet], to make it discoverable.

**Comment by Tbaut** [comment]
I fucked up the conflict resolution sorry, fixing this while reviewing :)

**Comment by wirednkod** [comment]
@Tbaut i have already added the Link so there may be a conflict. I would remove that here

**Comment by Tbaut** [comment]
@wirednkod I let you review this PR before merging, but since she was first to propose the PR, I think it'd be amazing if you can just pick up on her changes :pray: :heart:

**Review by Tbaut — APPROVED** [review]
Thanks a lot

**Review by wirednkod — APPROVED** [review]

**Pull request merged**
